### ISSUE TITLE
Loading weights of other pretrained CLIP version into this code

### ISSUE THREAD

**Issue by ariel415el** [moein-shariatnia/OpenAI-CLIP#22]
Hello, did anyone try to adapt the code so that we will be able to use pretrained weights of CLIP/openCLIP with this simple codebase?

**Comment by moein-shariatnia** [comment]
That would be tricky as the backbones I used in this repo are different (simpler, smaller) from what has been used in the original CLIP paper.

**Comment by ariel415el** [comment]
I saw you are using ResNet50. Isn't it one of the architecture used by the original clip?

**Comment by moein-shariatnia** [comment]
Yes, the vision encoder is similar. However, I'm using DistillBERT as text encoder and as far as I can recall, the way I implemented the projection heads are a bit different from what they used (some differences in activation functions and num of layers). It's not impossible ofc, but it may take some time to make it work.

**Comment by ariel415el** [comment]
Oh I see, Thank you for the help and for sharing this great project
