### ISSUE TITLE
can't reproduce

### ISSUE THREAD

**Issue by safakkbilici** [moein-shariatnia/OpenAI-CLIP#3]
I tried the code in notebook file, on flicker dataset. However results are not seen correct. Were the hyperparameters that you used for your training same as in notebook (especially number of epochs)? Do you have any model checkpoints as link? Thanks.

**Comment by moein-shariatnia** [comment]
> 

Hey @safakkbilici , thanks for informing me on this. Yes, I used the same hyperparameters and setup as in the notebook and I am surprised to hear that you could not reproduce the results. For the number of epochs, I once used 2 epochs and that was enough too!

I have a [demo notebook on Kaggle](https://www.kaggle.com/code/moeinshariatnia/openai-clip-simple-implementation/notebook) where you can find another similar training setup and also the model's checkpoint after training.

I hope that helps. Please let me know if you could overcome the problem.

**Comment by safakkbilici** [comment]
Hello again. I tried your notebook in Kaggle, and it worked perfectly. I think I missed something before. Thanks for your reply, have a good day.
